bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='ranking'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <span class="logo">Bookmarks</span>
        {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == "dashboard" %}class="selected"{% endif %}>
                    <a href="{% url "dashboard" %}">My dashboard</a>
                </li>
                    <li {% if section == "images" %}class="selected"{% endif %}>
                <a href="{% url 'images:list' %}">Images</a>
                    </li>
                <li {% if section == "people" %}class="selected"{% endif %}>
                    <a href="{% url 'user_list' %}">People</a>
                </li>
            </ul>
        {% endif %}
        <span class="user">
            {% if request.user.is_authenticated %}
                Hello {{ request.user.first_name|default:request.user.username }},
                <a href="{% url "logout" %}">Logout</a>
            {% else %}
                <a href="{% url "login" %}">Log-in</a>
            {% endif %}
        </span>
    </div>
    
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                <a href="#" class="close">x</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
    <script>
        const csrftoken = Cookies.get('csrftoken');
        document.addEventListener('DOMContentLoaded', (event) => {
        // DOM загружена
         {% block domready %} 
        {% endblock %}
    })
    </script>
</body>
</html>